/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class institute_nautilus_web4factory_LibFactory */

#ifndef _Included_institute_nautilus_web4factory_LibFactory
#define _Included_institute_nautilus_web4factory_LibFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     institute_nautilus_web4factory_LibFactory
 * Method:    a
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_institute_nautilus_web4factory_LibFactory_a
  (JNIEnv *, jobject);

/*
 * Class:     institute_nautilus_web4factory_LibFactory
 * Method:    b
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_institute_nautilus_web4factory_LibFactory_b
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
